### ISSUE TITLE
Add slug field 

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/tt_address#181]
Add slug field and update wizard

**Comment by KonstantinSoelch** [comment]
Since Georg requested it here's my Configuration:

Route Enhancer:
```
AddressPlugin:
    type: Extbase
    extension: TtAddress
    plugin: ListView
    routes:
      - routePath: '/{address_slug}'
        _controller: 'Address::show'
        _arguments:
          address_slug: address
    aspects:
      address_slug:
        type: PersistedAliasReplaceMapper
        replaceSource: ' '
        replaceTarget: '-'
        toLower: 1
        tableName: tt_address
        routeFieldName: name
```

Custom Mapper:

```
<?php

namespace Vendor\Name\Routing\Aspect;

use TYPO3\CMS\Core\Routing\Aspect\PersistedAliasMapper;
use TYPO3\CMS\Core\Site\SiteLanguageAwareTrait;

class PersistedAliasReplaceMapper extends PersistedAliasMapper
{
    use SiteLanguageAwareTrait;
    
    protected $replaceSource;
    protected $replaceTarget;
    protected $toLower;
    
    public function __construct(array $settings)
    {
        parent::__construct($settings);
        
        $this->replaceSource = $settings['replaceSource'] ?? '';
        $this->replaceTarget = $settings['replaceTarget'] ?? '';
        $this->toLower = $settings['toLower'] ?? false;
    }
    
    /**
     * {@inheritdoc}
     */
    public function generate($value): ?string
    {
        
        $route = str_replace($this->replaceSource, $this->replaceTarget, parent::generate($value));
        
        if($this->toLower == true) {
            $route = strtolower($route);
        }
        
        return $route;
    }
}
```
