### ISSUE TITLE
Routing in 9 example

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/tt_address#231]
```
  TtAddress:
    type: Extbase
    limitToPages:
      - 70
    extension: TtAddress
    plugin: ListView
    routes:
      -
        routePath: '/{address_title}'
        _controller: 'Address::show'
        _arguments:
          address_title: address
    defaultController: 'Address::list'
    aspects:
      address_title:
        type: PersistedAliasMapper
        tableName: tt_address
        routeFieldName: slug
```
