### ISSUE TITLE
pagination with routeEnhancer not working

### ISSUE THREAD

**Issue by bavarianbytes** [FriendsOfTYPO3/tt_address#384]
## Bug Report

**Current Behavior**
Not sure if it's bug or my config is wrong. I tried to add a routeEnhancer for pagination of the list view.
The pagination works, URLs are correct (e.g. `domain.com/addresses/page-2`), but no matter on which page i am, the address items of page 1 are rendered.
Seems like the `currentPage` param isn't reflected by the controller.

This is the routeEnhancer:
```
  TtAddress:
    type: Extbase
    extension: TtAddress
    plugin: ListView
    routes:
      -
        routePath: '/{address_title}'
        _controller: 'Address::show'
        _arguments:
          address_title: address
      -
        routePath: '/{page-label}-{page}'
        _controller: 'Address::list'
        _arguments:
          page: 'currentPage'
    defaultController: 'Address::list'
    aspects:
      address_title:
        type: PersistedAliasMapper
        tableName: tt_address
        routeFieldName: slug
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      page-label:
        type: LocaleModifier
        default: seite
        localeMap:
          -
            locale: 'en_.*'
            value: page
          -
            locale: 'it_.*'
            value: pagina
          -
            locale: 'fr_.*'
            value: page
          -
            locale: 'es_.*'
            value: pagina
```

**Expected behavior/output**
Paginated pages should show the correct address items.

**Environment**
- TYPO3 version(s): 10.4.21
- tt_address version: 5.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: OSX
