### ISSUE TITLE
Geocode Task is not registered in Typo3 11.5

### ISSUE THREAD

**Issue by christophrunkel** [FriendsOfTYPO3/tt_address#422]
## Bug Report

The geocode task is not available in scheduler->console command.

**Environment**

- TYPO3 version(s): [e.g. 11.5.16]
- tt_address version: [e.g. 6.1.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]

**Possible Solution**

Change Configuration/Services.yaml  and adding the command in lines 6ff makes it work:

```
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\TtAddress\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
   
  FriendsOfTYPO3\TtAddress\Command\GeocodeCommand:
    tags:
      - name: 'console.command'
        command: 'ttaddress:geocode'
        description: 'Geocode it'
        schedulable: true
        hidden: false
```
